### ISSUE TITLE
Checkout Page Not redirecting to Razorpay

### ISSUE THREAD

**Issue by iamafriedburrito** [Sukomal07/learning-management-system#1]
Steps to reproduce:
1. clone the project
2. install dependencies
3. run client and server deps
4. setup .env files
5. run server and client
6. add course via admin panel
8. click on subscribe button 
9. Get error "Something went wrong! Please try again later" Toast 

Code malfunction:

    async function handleSubscription() {
        if (!razorpay.key || !razorpay.subscription_id) { //this line becomes false in Checkout.jsx hence razorpay doesnt load
            console.log(razorpay.key)
            console.log(razorpay.subscription_id)
            toast.error("Something went wrong! Please try again later")
            return;
        }
  
 razorpay.subscription_id is undefined when logged hence if condition is trigged
 
 Can u please help?

**Comment by Sukomal07** [comment]
you need to create a subscription in razorpay . After that you will get subscription_id

**Comment by anuragk946667** [comment]
What is the email , password of admin login as I want to add courses plz help
